### ISSUE TITLE
Update the (official) Debian package

### ISSUE THREAD

**Issue by fd0** [restic/restic#1085]
Hi,

I'd like to discuss what we (as a project) can do to encourage having more up to date official Debian package in testing/unstable (not in stable obviously). Last weekend 0.7.0 has been released, but the Debian package (even in experimental) is still stuck at 0.5.0 uploaded in May (released in March): https://tracker.debian.org/pkg/restic

I acknowledge that releases which happen every four to five weeks is causing a lot of work, so I'd like to smooth the process as much as possible. Disclosure: I was a Debian maintainer once, so I'm familiar with the process.

@legrostdg thank you very much for taking care of the Debian package! Is there anything we can do to make it easier for you to update the package? Would you like help from other Debian maintainers?

I've also noticed that the git repository that was used to work on the package is unavailable: https://git.gueux.org/restic.git I can offer to create a repo within the GitHub organisation if you like.

CC @stapelberg @mika @jannic @xor-gate @sjoerd-ccu @jmallach @formorer

**Comment by xor-gate** [comment]
There are two ways to go:

* Generate an installable debian package (not more not less), from a generator script -> not debian dependant 
* Generate an debian package which is according to all debian guidelines, uses the debian/* directory structure and `debbuild` -> debian dependant

Syncthing uses the [fpm](https://github.com/jordansissel/fpm) to generate debian packages instead of all the files `debian/*` (see [syncthing/build.go](https://github.com/syncthing/syncthing/blob/322bedbb04943c8e139c6eda0b57c9824a4c6947/build.go#L512-L568). The point is you want building debian packages without actually running under debian. We currently use [xor-gate/debpkg](https://github.com/xor-gate/debpkg) to generate debian packages directly from golang (without any dependencies to debian script).

I'm not sure what the exact way to go is.

**Comment by stapelberg** [comment]
Are we talking about creating Debian packages to be installed from a third-party repository, or Debian packages for inclusion in Debian?

**Comment by xor-gate** [comment]
Those are indeed two separate things, probably IMHO we are talking about selfhosting an repository for the produced debian packages.

**Comment by fd0** [comment]
This issue is about the official Debian packages. We may decide to offer our own packages, but I'd rather like to get the official packages into shape and regularly updated.

**Comment by xor-gate** [comment]
Maybe you should update the issue title then which includes the "official" word. For official debian packaging we need a good maintainer. Which i'm not :+)

**Comment by stapelberg** [comment]
I can get this package into pkg-go (including the correspondig git repository on alioth), if the current maintainer is okay with that. Updates should then be quick, providing they don’t add new dependencies which aren’t yet packaged in Debian.

**Comment by zcalusic** [comment]
Yet, I'm unsure that this could work for Debian official releases. So called point releases (9.1, 9.2...) are usually only for security fixes and grave bug fixes. It's tough luck, but that's the way Debian release cycle works. Of course, for testing/unstable, the package could be updated as often as required.

More info here: https://wiki.debian.org/DebianReleases/PointReleases

**Comment by stapelberg** [comment]
For older stable releases, we can upload packages to the Debian backports repositories.

**Comment by fd0** [comment]
Good point! That should be our goal for the packages.

**Comment by jannic** [comment]
There is at least one new dependency, github.com/kurin/blazer/b2, which is not yet available in debian. So upgrading the package is more work than just compiling the latest version.

**Comment by stapelberg** [comment]
Right. I was trying to make a more general statement: the amount of work for packaging a new version increases with each additional dependency the new version requires. Conversely, if no new dependencies are added, packaging a new version is usually straight-forward.

For this specific version bump, we’ll need to make the package conform to pkg-go standards first, which wasn’t trivial the last time I had a look at this package.

**Comment by fd0** [comment]
I can suppose that using [gb](https://getgb.io) for this repo is complicating the process for a package. Basically, the restic repo is its own `GOPATH`: It has a `src` directory, and the code lives in the `restic` package (without a `github.com/restic/` prefix).

It is compatible with the stardard `go` tool though, just set `GOPATH` to `$PWD:$PWD/vendor`. For pkg-go, I think the `vendor` dir is not used (all dependencies should be in proper packages), so the `GOPATH` needs to be set to the global `GOPATH` (with the dependencies) and the repo root directory. So the following command can be used to compile restic:
```
$ GOPATH=/usr/share/gocode:$PWD \
  go build -s -w \
  -ldflags "-X main.version=0.7.1" \
  -o restic cmds/restic
```

I don't know how we can achieve that with pkg-go, though.

**Comment by stapelberg** [comment]
Our tooling drops the vendor directory, correct. I assume the `-s -w` ldflags are not necessary for compilation, are they?

**Comment by fd0** [comment]
The parameters are not required, no. `-s -w` disable omitting symbol table and debug information (see [here](https://golang.org/cmd/link/)). Setting a proper version (including the Debian release) with `-ldfags "-X main.version=[...]"` for restic to display is a good idea. Otherwise restic will only display:
```
$ ./restic version
restic compiled manually
compiled with go1.8.3 on linux/amd64
```

**Comment by jannic** [comment]
Some good news: After removing all references to b2 from restic, and upgrading golang-github-spf13-pflag-dev and golang-github-minio-minio-go-dev to the versions from experimental, the restic package compiles successfully with version 0.7.0.

So the number of missing dependencies is rather small.

(I just took the 0.5.0 package from experimental and replaced the source code with restic 0.7.0, so I skipped the move to pkg-go.)

**Comment by fd0** [comment]
I can also assist in bugging upstream library maintainers (e.g. minio-go, swift) to make a new release. It seems restic triggers quite a few edge cases.

**Comment by stapelberg** [comment]
I think the blockers are not so much the technical stuff, but the lack of an okay from the current maintainer.

**Comment by fd0** [comment]
Let's wait a bit what he says :)

**Comment by legrostdg** [comment]
Hi! Sorry, I've been offline during the last weeks.

I've prepared the upload of 0.6.1 to experimental in early June, but we need updated versions of the dependencies.
- `golang-github-spf13-pflag`: OK, updated to `0.0~git20170418.0.2300d0f-1`
- `golang-github-go-ini-ini`: has to be updated to `1.27.0-1`. I've prepared the package but there are problems. see #862755 https://lists.debian.org/debian-mentors/2017/06/msg00130.html
I just fixed the easy ones, but we have to find why the other packages fail to build.

Here is my checklist:
- `golang-github-ncw-swift`: has to be updated to `bf51ccd3b5`
- `golang-github-kurin-blazer`: has to be uploaded to sid
- `golang-github-minio-minio-go`: has to be updated to `fe53a65ebc43b5d22626b29a19a3de81170e42d3`
- `golang-github-mitchellh-go-homedir-dev`: has to be added as a build-dep (needed by minio-go. They use a fork but this one should be OK)
- `golang-github-spf13-cobra`: check if it has to be updated
- doc should be generated

It would certainly help if restic used only released versions of the dependencies (if available). At least, it would help to have a new release of minio-go.

The hard part is not updating restic, but the dependencies (and their reverse-dependencies).

@stapelberg for sure, you can hijack the package for `pkg-go`!

**Comment by legrostdg** [comment]
Concerning minio-go, I've just seen that v3.0.0 is available. Would it be possible to update it in restic and make a new 0.7.1 release?

**Comment by stapelberg** [comment]
@legrostdg Thanks for confirming. I’m currently traveling, but I’ll see when I can squeeze some packaging cleanup in for making restic confirm to pkg-go :).

**Comment by fd0** [comment]
Nice, thanks a lot!

**Comment by stapelberg** [comment]
Alright, I converted the package to pkg-go standards, see https://anonscm.debian.org/cgit/pkg-go/packages/restic.git

@legrostdg Do you want to have a look at this before I upload 0.5.0-2 to unstable? That gets the pkg-go related changes pushed; I’ll work on getting the new upstream version in right after that.

**Comment by fd0** [comment]
@stapelberg, nice! thanks a lot for your work!

**Comment by legrostdg** [comment]
@stapelberg I just had a look, it looks great. Thanks a lot!

I also had a look to the dependencies. @fd0 you did not answer my questions concerning this. Could restic use released versions (if available) of dependencies? In particular, I've seen that you updated minio-go to bd8e1d8a93. Is there something needed that is not in v3.0.0?

**Comment by stapelberg** [comment]
> @stapelberg I just had a look, it looks great. Thanks a lot!

Thanks for having a look. I plan to take a stab at the newer version/dependencies later today.

> I also had a look to the dependencies. @fd0 you did not answer my questions concerning this. Could restic use released versions (if available) of dependencies? In particular, I've seen that you updated minio-go to bd8e1d8a93. Is there something needed that is not in v3.0.0?

I suppose that switching to `dep` (as discussed in issue #1116) with its version constraints should make the situation clearer than it currently is.

**Comment by legrostdg** [comment]
OK, great! The dependencies were really painful to deal with for the debian package.

**Comment by fd0** [comment]
> I also had a look to the dependencies. @fd0 you did not answer my questions concerning this. Could restic use released versions (if available) of dependencies? In particular, I've seen that you updated minio-go to bd8e1d8a93. Is there something needed that is not in v3.0.0?

@legrostdg Oh, indeed. I'm not aware of anything that's not in v3.0.0, and updating the dependencies was also not really pleasant.

@stapelberg I had a quick look at the package, looks good!

**Comment by stapelberg** [comment]
Current status: golang-github-kurin-blazer is in NEW, and I replied to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862755 (golang-github-go-ini-ini), which will then unblock golang-github-minio-minio-go.

**Comment by legrostdg** [comment]
Great!

So, according to my checklist, after having golang-github-kurin-blazer-dev, we have to do this before building 0.7.0:
- golang-github-ncw-swift-dev should be updated to bf51ccd3b5 (golang-github-docker-distribution-dev also build-depends on this)
- golang-github-minio-minio-go-dev should be updated to fe53a65ebc43b5d22626b29a19a3de81170e42d3 (and should build depend on golang-github-mitchellh-go-homedir-dev)

I think golang-github-minio-minio-go should also be converted to the same layout as the other pkg-go's repos, but the last time the last uploader after me disagreed...

**Comment by stapelberg** [comment]
Yeah, I have minio on my bucket list (unless you want to do it?). The repo conversion is something I want to do as well, because the current one breaks `gbp dch` (at least for me), which I find unacceptable.

**Comment by legrostdg** [comment]
I think you will have a bigger authority than mine when converting the repo (and maybe arguing with the previous last uploader as we disagreed on this when I last updated the package). Furthermore, you will certainly do a better job than me for the conversion!

**Comment by stapelberg** [comment]
Alright, I’ll pick this fight then :). FWIW, the conversion is as simple as removing the “merge” option from debian/gbp.conf before doing `gbp import-orig --uscan`.

**Comment by fd0** [comment]
Thanks a lot for your work already!

**Comment by stapelberg** [comment]
I uploaded go-minio 3.0.0. Unfortunately, restic 0.7.0 depends on an older version of minio and fails to build with 3.0.0:

```
# github.com/restic/restic/src/restic/backend/s3
src/github.com/restic/restic/src/restic/backend/s3/s3.go:459: undefined: minio.CopyConditions
src/github.com/restic/restic/src/restic/backend/s3/s3.go:459: too many arguments in call to coreClient.Client.CopyObject
	have (string, string, string, <T>)
	want (minio.DestinationInfo, minio.SourceInfo)
```

I fixed this with the following patch, but I haven’t verified whether it works, so please do that and upstream it:

```diff
Index: restic/src/restic/backend/s3/s3.go
===================================================================
--- restic.orig/src/restic/backend/s3/s3.go
+++ restic/src/restic/backend/s3/s3.go
@@ -456,11 +456,16 @@ func (be *Backend) Rename(h restic.Handl
 	debug.Log("  %v -> %v", oldname, newname)
 
 	coreClient := minio.Core{Client: be.client}
-	err := coreClient.CopyObject(be.cfg.Bucket, newname, path.Join(be.cfg.Bucket, oldname), minio.CopyConditions{})
+	dst, err := minio.NewDestinationInfo(be.cfg.Bucket, newname, nil, nil)
 	if err != nil {
 		debug.Log("copy failed: %v", err)
 		return err
 	}
+	src := minio.NewSourceInfo(be.cfg.Bucket, oldname, nil)
+	if err := coreClient.CopyObject(dst, src); err != nil {
+		debug.Log("copy failed: %v", err)
+		return err
+	}
 
 	return be.client.RemoveObject(be.cfg.Bucket, oldname)
 }
```

Afterwards, the package compiles, but doesn’t successfully run tests yet. I’ll look into that.

**Comment by stapelberg** [comment]
The failing test was the FUSE test, and I think FUSE just isn’t supported in `schroot`s (which Debian uses for building). I’ve disabled them for now.

The package now builds, so we’re now only blocked on `golang-github-kurin-blazer` clearing the NEW queue.

**Comment by fd0** [comment]
I've already fixed this in the master branch, these two commits are relevant:
https://github.com/restic/restic/commit/68a91d66b76dfc9831b9aae296be65ee2b389c9d
https://github.com/restic/restic/commit/89ace85903330e79ca6bb418f9b4ba99f70c7072

I'll release 0.7.1 this weekend (at least that's the plan) including the two commits.

**Comment by fd0** [comment]
0.7.1 is released, it is based on minio-go v3.0.0. And I've bugged a few people to do releases of their libraries. And #1126 is in the works to switch to the default git repo layout.

**Comment by stapelberg** [comment]
golang-github-kurin-blazer made it into unstable, so I’m currently working on polishing the restic package. There are a few things to adjust due to the switch from markdown to restructuredtext, for example.

By the way, is there a manpage for the `restic` binary available somewhere? If not, could one be added? Debian requires all binaries to be accompanied by a manpage.

**Comment by fd0** [comment]
That'd be #697, we don't have a manpage yet.

**Comment by fd0** [comment]
@stapelberg The CLI framework we're using (cobra) can generate (basic) manpages from the help documentation. At the moment, I can quickly generate manpages for each restic command separately, is this the way to go nowadays? Have one manpage for every sub-command? `restic-backup`, `restic-snapshots`, etc?

**Comment by stapelberg** [comment]
I already uploaded 0.7.1, so take your time (including the change in the 0.7.2 release would be great).

Having individual manpages for subcommands is fine, as long as there is one manpage for the restic binary itself, which then refers to the subcommand manpages.

**Comment by fd0** [comment]
Okay, then that's the way to go. Thanks a lot for your work!

**Comment by stapelberg** [comment]
…and it’s in: https://packages.qa.debian.org/r/restic/news/20170727T073533Z.html.

This issue can now be closed.

**Comment by fd0** [comment]
Hu, that was fast. Thanks again!

The downside of having cobra generate the man pages is that we'll have more dependencies (at least at the time of manpage generation). But the upside is: hugo also uses these dependencies, so they are all already packagen in Debian :)
